apiVersion: apps/v1
kind: Deployment
metadata:
  name: studentcrud
  labels:
    app: studentcrud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: studentcrud
      
  template:
    metadata:
      labels:
        app: studentcrud
        
    spec:
      containers:
      - name: studentcrud
      
        image: vid45/dockerhub:myfirstimage
        imagePullPolicy: Always
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: studentcrud-svc
spec:
  selector:
    app: studentcrud
  ports:
  - port: 80
    targetPort: 8080
